name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: prepare .env
      run: cp env.sample .env
    - name: inject secrets
      env:
        MODEL_URL: ${{ secrets.MODEL_URL }}
        MODEL_TOKEN: ${{ secrets.MODEL_TOKEN }}
      run: |
        sed -i "s,<URL>,$MODEL_URL," configs/dynamic-plugins.yaml
        sed -i "s/<TOKEN>/$MODEL_TOKEN/" configs/dynamic-plugins.yaml
    - name: docker compose up
      run: docker compose up -d
    - name: Wait for HTTP 200 response from homepage
      run: |
        max=30
        i=0
        echo "Waiting for localhost to respond with status code 200..."
        until curl --head --fail http://localhost:7007; do
          i=$((i+1))
          if [ "$i" -ge "$max" ]; then
            echo "Max retries reached. Exiting."
            docker compose logs
            exit 1
          fi
          echo "($i/$max)Waiting for http://localhost:7007 to return HTTP 200..."
          sleep 5
        done
        echo "RHDH is ready!"
        curl --insecure http://localhost:7007
    - name: checkout tests
      uses: actions/checkout@v4
      with:
        repository: Katka92/lightspeed-e2e
        path: './e2e'
    - name: setup tests
      run: |
        cd e2e
        npm install
        npx playwright install --with-deps chromium
    - name: run tests
      run: |
        cd e2e
        npm test

